### ISSUE TITLE
Make a release, direct users to use from pypi

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/chws_tool#2]
I suggest doing a release (largely to confirm it works, all the config is working as intended) and then updating instructions to guide users to install from pypi (e.g. `pip install chrws_tool`)

**Comment by kojiishi** [comment]
Can you add PYPI secrets? The "Settings" tab does not appear for me.

**Comment by kojiishi** [comment]
If this should be in my PyPI account, I can create a token and send it to you. Please let me know.

**Comment by anthrotype** [comment]
I made you "admin" of this repo, you should now be able to access the secrets in the settings tab. You can use your PyPI token. I think you need to upload the very first time manually (using twine), then subsequently you become the owner of the project's page on PyPI and can create a new token with uplaod permissions and specific scope for the new package (will appear in the drop down menu in the Add API Token page in PyPI)

**Comment by kojiishi** [comment]
Thank you @anthrotype, I can see it now.

**Comment by kojiishi** [comment]
v1.0.0 released from github actions, seems to work fine, thank you for the great yaml in picosvg!
