### ISSUE TITLE
After running this tool, OTS warns: WARNING: Layout: tags aren't arranged alphabetically.

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/chws_tool#47]
I'm new to this tool, perhaps an issue on https://github.com/kojiishi/east_asian_spacing is more appropriate?

It seems add-chws doesn't properly sort the GPOS feature tags when building the features, which gets noticed by opentype-sanitizer:

    WARNING: Layout: tags aren't arranged alphabetically.

**Comment by kojiishi** [comment]
Fixed in [v1.4.1](https://github.com/googlefonts/chws_tool/releases/tag/v1.4.1), thank you for reporting this.
